import json
import logging
import re
import time
from typing import List, Dict, Any, Tuple, Optional
from groq import Groq
from pydantic import BaseModel, Field

from src.config import settings

logger = logging.getLogger(__name__)


class PlanOutput(BaseModel):
    """Structured plan output generated by the PlannerAgent."""
    sub_queries: List[str] = Field(
        ...,
        description="List of 2 to 4 distinct, targeted search queries to thoroughly investigate the topic."
    )
    rationale: str = Field(
        default="",
        description="Brief explanation of how these sub-queries cover the research problem."
    )


class PlannerAgent:
    """Agent responsible for decomposing a complex research question into focused sub-queries."""

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None):
        self.api_key = api_key or settings.groq_api_key
        self.model = model or settings.groq_model
        if not self.api_key:
            raise ValueError("Groq API key is missing. Please set GROQ_API_KEY in .env.")
        self.client = Groq(api_key=self.api_key)

    def plan(self, query: str, max_sub_queries: Optional[int] = None) -> Tuple[PlanOutput, Dict[str, Any]]:
        """
        Decomposes user query into 2-4 focused sub-queries.

        Args:
            query: The user's original research question.
            max_sub_queries: Max number of sub-queries (defaults to config setting).

        Returns:
            Tuple of (PlanOutput, token_usage_dict).
        """
        limit = max_sub_queries or settings.max_sub_queries
        limit = max(1, min(limit, 4))  # Constrain between 1 and 4

        system_prompt = (
            "You are a master Research Strategist and Planner AI. Your goal is to analyze a complex "
            "research question and decompose it into 2 to {limit} distinct, highly specific search queries.\n\n"
            "GUIDELINES:\n"
            "1. Each sub-query must target a distinct dimension of the question (e.g., technical definitions, comparisons, real-world benchmarks, trade-offs).\n"
            "2. Ensure queries are formatted as effective search engine queries (concise, clear, and keyword-rich).\n"
            "3. Do NOT produce redundant or overlapping queries.\n"
            "4. Return strictly valid JSON adhering to this structure:\n"
            "{\n"
            '  "sub_queries": ["query 1", "query 2", ...],\n'
            '  "rationale": "Brief 1-2 sentence reason for choosing these sub-queries"\n'
            "}"
        ).replace("{limit}", str(limit))

        user_prompt = f"Decompose this research question into {limit} focused search queries:\n\"{query}\""

        logger.info(f"Invoking PlannerAgent with model '{self.model}' for query: '{query}' (limit={limit})")

        try:
            chat_completion = self.client.chat.completions.create(
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                model=self.model,
                temperature=0.1,  # Low temperature for deterministic planning
                max_tokens=500,
                response_format={"type": "json_object"}
            )

            raw_content = chat_completion.choices[0].message.content
            usage = {
                "prompt_tokens": chat_completion.usage.prompt_tokens if chat_completion.usage else 0,
                "completion_tokens": chat_completion.usage.completion_tokens if chat_completion.usage else 0,
                "total_tokens": chat_completion.usage.total_tokens if chat_completion.usage else 0,
                "model": self.model
            }

            plan_output = self._parse_response(raw_content, query, limit)
            logger.info(f"PlannerAgent successfully generated {len(plan_output.sub_queries)} sub-queries.")
            return plan_output, usage

        except Exception as e:
            logger.warning(f"PlannerAgent failed or raised exception: {e}. Falling back to original query.")
            fallback_plan = PlanOutput(
                sub_queries=[query],
                rationale=f"Fallback to single query due to planner error: {str(e)}"
            )
            return fallback_plan, {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0, "model": self.model}

    def _parse_response(self, content: str, fallback_query: str, limit: int) -> PlanOutput:
        """Extracts and validates PlanOutput from JSON response string."""
        try:
            # Handle potential markdown code block wrappers
            clean_content = content.strip()
            if "```json" in clean_content:
                clean_content = clean_content.split("```json")[1].split("```")[0].strip()
            elif "```" in clean_content:
                clean_content = clean_content.split("```")[1].split("```")[0].strip()

            data = json.loads(clean_content)
            sub_queries = data.get("sub_queries", [])

            # Filter and sanitize sub-queries
            valid_queries = [q.strip() for q in sub_queries if isinstance(q, str) and q.strip()]

            if not valid_queries:
                raise ValueError("Parsed JSON contains empty sub_queries list.")

            # Enforce upper limit
            valid_queries = valid_queries[:limit]

            return PlanOutput(
                sub_queries=valid_queries,
                rationale=data.get("rationale", "")
            )

        except Exception as err:
            logger.warning(f"Failed to parse JSON planner output: {err}. Content was: {content[:200]}")
            return PlanOutput(
                sub_queries=[fallback_query],
                rationale=f"Fallback used due to parsing exception ({err})"
            )
