import time
import logging
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

from src.config import settings
from src.agents.planner_agent import PlannerAgent, PlanOutput
from src.agents.search_agent import SearchAgent
from src.agents.writer_agent import WriterAgent

logger = logging.getLogger(__name__)


class ResearchResult(BaseModel):
    """Container for the output of a research pipeline execution."""
    query: str
    sub_queries: List[str] = Field(default_factory=list)
    plan_rationale: str = ""
    report: str
    search_results: List[Dict[str, Any]]
    planning_time_sec: float = 0.0
    search_time_sec: float = 0.0
    synthesis_time_sec: float = 0.0
    total_time_sec: float = 0.0
    usage: Dict[str, Any] = Field(default_factory=dict)


class ResearchPipeline:
    """Three-Agent Pipeline coordinating PlannerAgent, SearchAgent, and WriterAgent."""

    def __init__(
        self,
        planner_agent: Optional[PlannerAgent] = None,
        search_agent: Optional[SearchAgent] = None,
        writer_agent: Optional[WriterAgent] = None
    ):
        settings.validate_keys()
        self.planner_agent = planner_agent or PlannerAgent()
        self.search_agent = search_agent or SearchAgent()
        self.writer_agent = writer_agent or WriterAgent()

    def run(
        self,
        query: str,
        max_sub_queries: Optional[int] = None,
        max_results_per_subquery: Optional[int] = None
    ) -> ResearchResult:
        """
        Executes the full 3-agent research loop (Plan -> Multi-Search -> Write).

        Args:
            query: The research question.
            max_sub_queries: Optional override for number of sub-queries generated by Planner.
            max_results_per_subquery: Optional override for results per sub-query.

        Returns:
            ResearchResult with plan breakdown, cited report, and telemetry.
        """
        if not query or not query.strip():
            raise ValueError("Research query cannot be empty.")

        query = query.strip()
        start_total = time.perf_counter()

        # Step 1: Execute Planner Agent
        start_planning = time.perf_counter()
        plan_output, planner_usage = self.planner_agent.plan(
            query=query,
            max_sub_queries=max_sub_queries
        )
        planning_time = time.perf_counter() - start_planning

        # Step 2: Execute Search Agent (Multi-Query with URL Deduplication)
        start_search = time.perf_counter()
        search_results = self.search_agent.search_multi(
            queries=plan_output.sub_queries,
            max_results_per_query=max_results_per_subquery
        )
        search_time = time.perf_counter() - start_search

        # Step 3: Execute Writer Agent
        start_synthesis = time.perf_counter()
        report, writer_usage = self.writer_agent.synthesize(
            query=query,
            search_results=search_results
        )
        synthesis_time = time.perf_counter() - start_synthesis

        total_time = time.perf_counter() - start_total

        # Aggregate total token usage across all LLM agents
        total_usage = {
            "model": writer_usage.get("model", settings.groq_model),
            "planner_prompt_tokens": planner_usage.get("prompt_tokens", 0),
            "planner_completion_tokens": planner_usage.get("completion_tokens", 0),
            "writer_prompt_tokens": writer_usage.get("prompt_tokens", 0),
            "writer_completion_tokens": writer_usage.get("completion_tokens", 0),
            "total_tokens": planner_usage.get("total_tokens", 0) + writer_usage.get("total_tokens", 0)
        }

        return ResearchResult(
            query=query,
            sub_queries=plan_output.sub_queries,
            plan_rationale=plan_output.rationale,
            report=report,
            search_results=search_results,
            planning_time_sec=round(planning_time, 2),
            search_time_sec=round(search_time, 2),
            synthesis_time_sec=round(synthesis_time, 2),
            total_time_sec=round(total_time, 2),
            usage=total_usage
        )


# Backward compatibility alias
TwoAgentPipeline = ResearchPipeline
